spring:
    application:
        name: marp

    profiles:
        active: dev  

    datasource:
        url: jdbc:postgresql://localhost:5432/marp  
        username: postgres
        password: 6337311
        driverClassName: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        database-platform: org.hibernate.dialect.PostgreSQLDialect 